package com.chenzeyi.util.itextpdf;

public class Paper implements  Cloneable {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.PAPER_NAME
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private String paperName;
	

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.PAPER_WIDTH
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer paperWidth;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.PAPER_HEIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer paperHeight;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.MARGIN_TOP
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer marginTop;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.MARGIN_LEFT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer marginLeft;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.MARGIN_BOTTOM
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer marginBottom;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.MARGIN_RIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private Integer marginRight;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.DESCRIPTION
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.RESERVE1
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private String reserve1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.RESERVE2
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private String reserve2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column SM_PAPER_TB.RESERVE3
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	private String reserve3;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.PAPER_NAME
	 * @return  the value of SM_PAPER_TB.PAPER_NAME
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public String getPaperName() {
		return paperName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.PAPER_NAME
	 * @param paperName  the value for SM_PAPER_TB.PAPER_NAME
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setPaperName(String paperName) {
		this.paperName = paperName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.PAPER_WIDTH
	 * @return  the value of SM_PAPER_TB.PAPER_WIDTH
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getPaperWidth() {
		return paperWidth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.PAPER_WIDTH
	 * @param paperWidth  the value for SM_PAPER_TB.PAPER_WIDTH
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setPaperWidth(Integer paperWidth) {
		this.paperWidth = paperWidth;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.PAPER_HEIGHT
	 * @return  the value of SM_PAPER_TB.PAPER_HEIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getPaperHeight() {
		return paperHeight;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.PAPER_HEIGHT
	 * @param paperHeight  the value for SM_PAPER_TB.PAPER_HEIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setPaperHeight(Integer paperHeight) {
		this.paperHeight = paperHeight;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.MARGIN_TOP
	 * @return  the value of SM_PAPER_TB.MARGIN_TOP
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getMarginTop() {
		return marginTop;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.MARGIN_TOP
	 * @param marginTop  the value for SM_PAPER_TB.MARGIN_TOP
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setMarginTop(Integer marginTop) {
		this.marginTop = marginTop;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.MARGIN_LEFT
	 * @return  the value of SM_PAPER_TB.MARGIN_LEFT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getMarginLeft() {
		return marginLeft;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.MARGIN_LEFT
	 * @param marginLeft  the value for SM_PAPER_TB.MARGIN_LEFT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setMarginLeft(Integer marginLeft) {
		this.marginLeft = marginLeft;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.MARGIN_BOTTOM
	 * @return  the value of SM_PAPER_TB.MARGIN_BOTTOM
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getMarginBottom() {
		return marginBottom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.MARGIN_BOTTOM
	 * @param marginBottom  the value for SM_PAPER_TB.MARGIN_BOTTOM
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setMarginBottom(Integer marginBottom) {
		this.marginBottom = marginBottom;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.MARGIN_RIGHT
	 * @return  the value of SM_PAPER_TB.MARGIN_RIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public Integer getMarginRight() {
		return marginRight;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.MARGIN_RIGHT
	 * @param marginRight  the value for SM_PAPER_TB.MARGIN_RIGHT
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setMarginRight(Integer marginRight) {
		this.marginRight = marginRight;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.DESCRIPTION
	 * @return  the value of SM_PAPER_TB.DESCRIPTION
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.DESCRIPTION
	 * @param description  the value for SM_PAPER_TB.DESCRIPTION
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.RESERVE1
	 * @return  the value of SM_PAPER_TB.RESERVE1
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public String getReserve1() {
		return reserve1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.RESERVE1
	 * @param reserve1  the value for SM_PAPER_TB.RESERVE1
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.RESERVE2
	 * @return  the value of SM_PAPER_TB.RESERVE2
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public String getReserve2() {
		return reserve2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.RESERVE2
	 * @param reserve2  the value for SM_PAPER_TB.RESERVE2
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column SM_PAPER_TB.RESERVE3
	 * @return  the value of SM_PAPER_TB.RESERVE3
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public String getReserve3() {
		return reserve3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column SM_PAPER_TB.RESERVE3
	 * @param reserve3  the value for SM_PAPER_TB.RESERVE3
	 * @ibatorgenerated  Sun Sep 22 15:05:28 CST 2013
	 */
	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}
	
	public Paper(Integer paperWidth, Integer paperHeight, Integer marginTop,
			Integer marginLeft, Integer marginBottom, Integer marginRight) {
		super();
		this.paperWidth = paperWidth;
		this.paperHeight = paperHeight;
		this.marginTop = marginTop;
		this.marginLeft = marginLeft;
		this.marginBottom = marginBottom;
		this.marginRight = marginRight;
	}
	
	public Paper() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Paper clone() {
		Paper paper = null;
		try {
			paper = (Paper) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return paper;
	}
}